services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: notifyhub
      POSTGRES_PASSWORD: notifyhub
      POSTGRES_DB: notifyhub
    ports:
      - "5432:5432"
    volumes:
      - notifyhub_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://notifyhub:notifyhub@postgres:5432/notifyhub
      JWT_SECRET_KEY: change_me
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 60

      REDIS_BROKER_URL: redis://redis:6379/0
      REDIS_RESULT_BACKEND_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "false"
      CELERY_TASK_EAGER_PROPAGATES: "true"

      EMAIL_SIMULATION_ENABLED: "true"
      EMAIL_FAILURE_RATE: "0.3"

      # OpenTelemetry distributed tracing
      OTEL_ENABLED: "true"
      OTEL_SERVICE_NAME: notifyhub-backend
      OTEL_EXPORTER_OTLP_ENDPOINT: ""
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://notifyhub:notifyhub@postgres:5432/notifyhub
      JWT_SECRET_KEY: change_me
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 60

      REDIS_BROKER_URL: redis://redis:6379/0
      REDIS_RESULT_BACKEND_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "false"
      CELERY_TASK_EAGER_PROPAGATES: "true"

      EMAIL_SIMULATION_ENABLED: "true"
      EMAIL_FAILURE_RATE: "0.3"

      # OpenTelemetry distributed tracing
      OTEL_ENABLED: "true"
      OTEL_SERVICE_NAME: notifyhub-worker
      OTEL_EXPORTER_OTLP_ENDPOINT: ""
    depends_on:
      - postgres
      - redis
    command: celery -A app.workers.celery_app worker --loglevel=INFO --concurrency=1

volumes:
  notifyhub_postgres_data:
