from alembic import op
import sqlalchemy as sa


revision = '{{ revision }}'
down_revision = '{{ down_revision }}'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

